### PR TITLE
Added a method (tuple_index) to the Namelist class that allows access…

### PR DESCRIPTION
**Pull request by jenssss**
… to an element using a tuple rather than the [][] syntax

### CODE REVIEW

**Comment by marshallward** [comment]
Thanks for this, I'll have a look tomorrow.

BTW you might be interested in #16 which enables access to fields with the deference ("dot") operator.  As far as I can tell, it's safe to use and would achieve something similar to the tuple operator.

**Comment by jenssss** [comment]
I just remembered why I wanted the tuple access method, it was to to work with the returns from the 'flat_iterator' method that I just added to the pull request. I didn't see a similar iterator in f90nml already, but I might have missed it.

**Comment by marshallward** [comment]
Thanks for sending this, some sort of iterator could be a useful feature.  If it's alright, I wouldn't mind talking through how it could work.

How do you see derived types being handled (dicts of dicts, e.g. `a%b%c = 1`), or if the output is a vector or list.  Do you see iteration over values?  Or just stick to the namelist groups and their top-level values?

I am wondering if it's practical to use this as a default iterator of the namelist (e.g. `next(nml)`). Dicts don't have intrinsic iterators, so maybe there is no definitive answer here.

I also think that maybe the tuple access ought to be made private (`_tuple_index`), since I can't really see a good use case on its own.

**Comment by marshallward** [comment]
Actually, it's probably more correct to say dicts contain multiple iterators (`for key in d`, `d.items()`, etc.).  It would be to confirm if this can be implemented using its intrinsic iterators.

**Comment by jenssss** [comment]
Sure, I'm fine with discussing what would be the best solution.

The iterator I had in mind is one that does not go any deeper than the two top levels of the namelist. I suppose it would be possible to write a recursive iterator like https://stackoverflow.com/a/10756615 to go deeper, but that is not what I had in mind. I was just thinking of an iterator to traverse the main two top-level structure of the namelist.

As for whether to make `tuple_index` private, I currently have the following use case. I want to compare two namelists, and do something if they have one entry different, but all others identical. For the 'something' I want to have the value of the namelist element at the place where the namelists differ, for both namelists. As far as I can tell, the simplest way of getting this is using the tuple_index method.

```
def get_index_for_all_but_one_changed(nl1,nl2):
    for key, value in nl1.flat_iterator(): 
        value2 = nl2.tuple_index(key)
        if value != value2:
            if namelists_eq(nl1,nl2,[key]): 
                yield key, value, value2

def namelists_eq(nl1,nl2,ignore_keys=[]):
    nl1_flat = flatten_namelist(nl1,ignore_keys)
    nl2_flat = flatten_namelist(nl2,ignore_keys)
    return nl1_flat == nl2_flat
def flatten_namelist(nl,ignore_keys=[]):
    return dict((key,value) for key, value in nl.flat_iterator() if key not in ignore_keys)
```

**Comment by marshallward** [comment]
Hi, sorry for the silence, I've been mentally invested in an unrelated project.

My first instinct is that `tuple_index` is quite simple, and maybe not necessary to include, if only because it's a single line and relatively easy to reproduce.  But I will continue to think about it, and feel free to make the case.

Having said that, I think that `flat_iterator` is quite similar to `items()` (or `iteritems()`) and could be a good addition.  Maybe rename it to something like `groups()` or `itergroups()` to keep it similar to `dict`?

Also, @aekiss has a similar project using `f90nml` to compare and validate namelists, [nmltab](https://github.com/aekiss/nmltab) and it might be nice to get his feedback on this problem.  @aekiss would these changes help you in your project?

**Comment by marshallward** [comment]
Actually I just saw your update to `tuple_index`, which is a bit more sophisticated, I'll think a bit more on it.

**Comment by marshallward** [comment]
Maybe a good solution here is to modify `__getitem__` to accept tuples, so that we could just do something like `nml['a', 'b']`?

This could initially just support group/value pairs, but could later be made recursive.

**Comment by aekiss** [comment]
Hi @jenssss am I right in thinking the function [nmldiff](https://github.com/aekiss/nmltab/blob/master/nmltab.py#L107) in [nmltab](https://github.com/aekiss/nmltab) solves a more general problem than your use case? It finds all differences between multiple namelists, including if a key is present in some of the namelists but not all of them.

Maybe it's not as elegant as it could be, but I'm satisfied with how it works so I wouldn't rewrite it to use tuple indexing.

**Comment by jenssss** [comment]
@marshallward, I think that modifying `__getitem__` is a great idea. I'm now thinking about how to do that.

I suppose that all the keys for the first level `OrderedDict` in  the `Namelist` class would always be strings, right? (It seems you're already assuming this, since you're using the `.lower()` method in the current `__getitem__`.) If so, I think the simplest way to modify `__getitem__` would be to check if the input is a string, if so do what is done now, else do new stuff.

Also, I don't think it necessarily has to be limited to tuples in `__getitem__`. Any iterable capable of returning at least 2 elements should do.

Renaming `flat_iterator()` is a good idea. I'm playing with the idea of something like `itergroups_names()`, since it iterates over both groups and names, although it is a bit long, so one of your suggestions might be better.

**Comment by jenssss** [comment]
Hi @aekiss. [nmltab](https://github.com/aekiss/nmltab) certainly looks very interesting, and I might be able to use it, although I don't think it exactly solves my problem.

I didn't explain it before, but what I want is to group namelists together, such that all namelists in one group are identical except for one element, in which they should all be different (I ignore namelists that are completely identical). As far as I can tell the diffs from `nmldiff` does not give these groupings, so you would still have to iterate and do comparisons over the diffs in my case.

This is of course easier to do with namelist diffs rather than full namelists, since then you have to iterate over far fewer elements.

**Comment by jenssss** [comment]
@marshallward How about my latest commit?

**Comment by marshallward** [comment]
Sorry again for the delay, this all looks good.  I might rework the `getitem` check to be a little more type-safe but otherwise it looks OK.

I'll have a play with it over the weekend, and should merge this soon.  Thanks!

**Comment by marshallward** [comment]
All good, thanks!

**Comment by marshallward** [comment]
Just a short followup here.  Two points:

1. I wonder if `groups` is not the right name here (which I admit was my suggestion), since the groups in this case are the keys of the namelist, rather than the ((group, variable), value) tuple.  I still don't know the right name here (`items` is obviously confusing) but it might be worth renaming this at some point.

2. It seems that similar methods in `dict` return a [view object](https://stackoverflow.com/questions/8957750/what-are-dictionary-view-objects) rather than an iterator.  I don't know if it's possible to even create a view object - they seem to be internally defined - but it might be worth looking into.  For example, a list might be closer to a view object than an iterator.

I don't forsee any immediate changes, so I've merged it all in.  I will ping you before going ahead with any of this.

**Comment by jenssss** [comment]
I just found out that `basestring`, which I used in the` __getitem__` method, does not exist in Python 3. The following could be used instead
```
from six import string_types
isinstance(s, string_types)
```
from 
[(https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility/11301392)]

**Pull request merged**
