### PR TITLE
Added option for sorted write (by group then variable).

### PR DESCRIPTION
**Pull request by aekiss**
Hi Marshall

This is handy for making canonical nml files which are easily compared, diffed, etc...

But perhaps it would be better to have a sort method for Namelists instead?

cheers
Andrew

### CODE REVIEW

**Comment by marshallward** [comment]
Yes I think a `sort` method in Namelist would be better.  An extra optional call seems better than adding an extra argument which does the same thing.

Or a property, if you want it to persist with new entries.

Also, `sel` is a weird variable name, no better suggestions yet.

**Comment by aekiss** [comment]
OK fair enough. I've added it as a Namelist property instead. Also changed 'sel' to 'nml' - possibly better...?

**Comment by marshallward** [comment]
Sorry to be a pain... but now that I understand this, I think it would be better as a function flag.

I had thought it was sorting the contents, rather than just the output.

How about I just manually merge in a04e239c7af077ccd7c25f68a6485d8be229d486 ?  Sorry for adding extra work for you.

**Comment by marshallward** [comment]
I've merged the first commit.

A sorted version sounds interesting, but we can work on this another time after resolving the duplicate group issue.

**Pull request closed without merging**
