### PR TITLE
Change ERROR type

### PR DESCRIPTION
**Pull request by singularitti**
Passing arguments of the wrong type (e.g. passing a list when an int is expected) should result in a TypeError, but passing arguments with the wrong value (e.g. a number outside expected boundaries) should result in a ValueError.

### CODE REVIEW

**Comment by marshallward** [comment]
Thanks for sending this, could you resend it without the whitespace changes?  Also it seems you removed the arch package file.

**Comment by singularitti** [comment]
Sure, in a moment.

**Comment by singularitti** [comment]
Is it OK now? Thanks!

**Comment by marshallward** [comment]
Thanks this looks good.  (There was a slight change to the arch .gitignore, but I'll revert that if it's a problem).  I'm a little baffled why the coverage dropped, but it's probably has something to do with Travis support for Python 2.6.

Thanks for catching this, you would have had to look rather deeply to find something like that :).

**Comment by singularitti** [comment]
You are welcome. Because I really like this package!

**Pull request merged**
